routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('notes.index');
});

Route::resource('notes', 'NoteController');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable = [
        'content',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    protected function renderJsonOrBlade($payload, $blade = null)
    {
        $request = request();

        if ($blade === null || $request->wantsJson() || $request->is('api/*')) {
            return response()->json($payload);
        }

        return view($blade, $payload);
    }

    protected function renderJsonOrRedirectTo($payload, $url = null)
    {
        $request = request();

        if ($url === null || $request->wantsJson() || $request->is('api/*')) {
            return response()->json($payload);
        }

        return redirect($url);
    }

    protected function renderJsonOrRedirectBack($payload)
    {
        $request = request();

        if ($request->wantsJson() || $request->is('api/*')) {
            return response()->json($payload);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\NoteRequest;
use \App\Note;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Note::get();
        return $this->renderJsonOrBlade([
            'notes' => $notes,
        ], 'notes.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\NoteRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NoteRequest $request)
    {
        $note = new Note($request->all());
        $note->save();
        return $this->renderJsonOrRedirectTo([
            'note' => $note,
        ], route('notes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $note = Note::find($id);
        return $this->renderJsonOrBlade([
            'note' => $note,
        ], 'notes.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $note = Note::find($id);
        return view('notes.edit', [
            'note' => $note,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\NoteRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NoteRequest $request, $id)
    {
        $note = Note::findOrFail($id);
        $note->fill($request->all());
        $note->save();
        return $this->renderJsonOrRedirectTo([
            'note' => $note,
        ], route('notes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Note::find($id);
        $note->delete();
        return $this->renderJsonOrRedirectBack([
            'note' => $note,
        ]);
    }
}

resources/views/notes/_form.blade.php
<form method="POST" action="{{ $action }}">
    <div class="form-group">
        <label for="content">Content</label>
        <textarea
            class="form-control {{ $errors->has('content') ? 'is-invalid' : '' }}"
            id="content"
            rows="8"
            name="content">{{ $note->content }}</textarea>
        @if($errors->has('content'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('content') }}</strong>
            </span>
        @endif
    </div>
    @csrf
    @method($method)
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{{ route('notes.index') }}" class="btn btn-light">Back</a>
</form>

resources/views/notes/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Note</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <div style="max-width: 500px; margin: auto;">
            <h1 class="mb-3 mt-4">New Note</h1>
    
            @include('notes._form', [
                'note' => new App\Note(),
                'action' => route('notes.store'),
                'method' => 'post',
            ])
        </div>
    </body>
</html>

resources/views/notes/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Note</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <div style="max-width: 500px; margin: auto;">
            <h1 class="mb-3 mt-4">Update Note</h1>
    
            @include('notes._form', [
                'note' => $note,
                'action' => route('notes.update', ['id' => $note->id]),
                'method' => 'put',
            ])
        </div>
    </body>
</html>

resources/views/notes/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Notes</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <div style="max-width: 500px; margin: auto;">
            <h1 class="mb-3 mt-4">Notes</h1>
    
            <ul class="list-group">
                @foreach($notes as $note)
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ route('notes.show', ['id' => $note->id]) }}">
                            {{ substr($note->content, 0, 30) }}...
                        </a>
                        <div>
                            <a href="{{ route('notes.edit', ['id' => $note->id]) }}" class="btn btn-outline-primary btn-sm">Edit</a>
                            <form 
                                style="display: inline;"
                                method="POST"
                                action="{{ route('notes.destroy', ['id' => $note->id]) }}">
                                @csrf
                                @method('delete')
                                <button onclick="return confirm('確定要刪除？');" type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </div>
                    </li>
                @endforeach
                <a href="{{ route('notes.create') }}" class="btn btn-primary mt-3">Create</a>
            </ul>
        </div>
    </body>
</html>

resources/views/notes/show.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Note</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    </head>
    <body>
        <div style="max-width: 500px; margin: auto;">
            <h1 class="mb-3 mt-4">Note Detail</h1>
    
            <pre style="white-space: pre-wrap;">{{ $note->content }}</pre>

            <a href="{{ route('notes.index') }}" class="btn btn-primary">Back</a>
        </div>
    </body>
</html>